### ISSUE TITLE
Stable

### ISSUE THREAD

**Issue by AdrienChampion** [ufmg-smite/lean-smt#74]
I wanted to use lean-smt in a `stable` project, and noticed it's pinned to `v4.2.0-rc1`.

In case you're interested in a PR, I made [a `stable` version here](https://github.com/AdrienChampion/lean-smt/tree/to_stable) which was relatively straightforward. There are a few changes that would need to be reviewed ([here](https://github.com/ufmg-smite/lean-smt/compare/main...AdrienChampion:lean-smt:to_stable?expand=1#diff-39cd8fb15caa911dec9267c5be927af99aad5f6c689fcfcb94c5fd8cb93215abR180), [here](https://github.com/ufmg-smite/lean-smt/compare/main...AdrienChampion:lean-smt:to_stable?expand=1#diff-39cd8fb15caa911dec9267c5be927af99aad5f6c689fcfcb94c5fd8cb93215abR190), and [here](https://github.com/ufmg-smite/lean-smt/compare/main...AdrienChampion:lean-smt:to_stable?expand=1#diff-c25dd5380e83c330e701b23345366dbb59aac530f18bb871d414926b740cc085R343) at least), but nothing major.

**Comment by abdoo8080** [comment]
Hi @AdrienChampion! Thank you for the helpful note. The last two commits move the pin to v4.4.0.

**Comment by AdrienChampion** [comment]
Awesome!
